# Generated by Django 4.2.9 on 2025-11-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aktenverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahlungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag_soll', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('betrag_haben', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Anstehend', 'Anstehend'), ('Ausstehend_Abgleich', 'Ausstehend_Abgleich'), ('Abgeschlossen', 'Abgeschlossen')], default='Anstehend', max_length=50)),
                ('beschreibung', models.CharField(blank=True, max_length=255)),
                ('faellig_am', models.DateField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('akte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to='aktenverwaltung.akte')),
            ],
            options={
                'ordering': ['status', 'faellig_am'],
            },
        ),
    ]
