# Generated by Django 4.2.9 on 2025-11-17 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aktenverwaltung", "0001_initial"),
        ("finanzen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zahlungsposition",
            options={},
        ),
        migrations.RemoveField(
            model_name="zahlungsposition",
            name="betrag_haben",
        ),
        migrations.RemoveField(
            model_name="zahlungsposition",
            name="betrag_soll",
        ),
        migrations.RemoveField(
            model_name="zahlungsposition",
            name="faellig_am",
        ),
        migrations.AddField(
            model_name="zahlungsposition",
            name="aktualisiert_am",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="zahlungsposition",
            name="betrag",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="zahlungsposition",
            name="datum",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="zahlungsposition",
            name="akte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zahlungspositionen",
                to="aktenverwaltung.akte",
            ),
        ),
        migrations.AlterField(
            model_name="zahlungsposition",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFFEN", "Offen"),
                    ("ABGLEICH", "Abgleich"),
                    ("BEZAHLT", "Bezahlt"),
                    ("STORNO", "Storno"),
                ],
                default="OFFEN",
                max_length=50,
            ),
        ),
    ]
