# Generated by Django 4.2.9 on 2025-11-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('aktenzeichen', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Offen', 'Offen'), ('Geschlossen', 'Geschlossen'), ('Archiviert', 'Archiviert')], default='Offen', max_length=50)),
                ('info_zusatz', models.JSONField(blank=True, default=dict)),
                ('mandant_historie', models.JSONField(blank=True, default=dict)),
                ('gegner_historie', models.JSONField(blank=True, default=dict)),
                ('dokumenten_pfad_root', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-aktualisiert_am'],
            },
        ),
        migrations.CreateModel(
            name='Gegner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('bankverbindung', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mandant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('bankverbindung', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=255)),
                ('dateiname', models.CharField(max_length=255)),
                ('pfad_auf_server', models.CharField(max_length=512)),
                ('akte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='aktenverwaltung.akte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='akte',
            name='gegner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gegner_akten', to='aktenverwaltung.gegner'),
        ),
        migrations.AddField(
            model_name='akte',
            name='mandant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akten', to='aktenverwaltung.mandant'),
        ),
    ]
