# Generated by Django 4.2.9 on 2025-11-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gegner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gegner',
            name='telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gegner',
            name='typ',
            field=models.CharField(choices=[('Person', 'Person'), ('Firma', 'Firma'), ('Versicherung', 'Versicherung')], default='Person', max_length=20),
        ),
        migrations.AddField(
            model_name='mandant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mandant',
            name='telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mandant',
            name='typ',
            field=models.CharField(choices=[('Person', 'Person'), ('Firma', 'Firma'), ('Versicherung', 'Versicherung')], default='Person', max_length=20),
        ),
    ]
