# Generated by Django 5.2.8 on 2025-11-19 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0002_gegner_email_gegner_telefon_gegner_typ_mandant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
