# Generated by Django 5.2.8 on 2025-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0003_dokument_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drittbeteiligter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('typ', models.CharField(choices=[('Person', 'Person'), ('Firma', 'Firma'), ('Versicherung', 'Versicherung')], default='Person', max_length=20)),
                ('rolle', models.CharField(blank=True, help_text='z.B. Zeuge, Sachverständiger, etc.', max_length=100)),
                ('notizen', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Drittbeteiligte',
            },
        ),
    ]
