# Generated by Django 5.2.8 on 2025-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0004_drittbeteiligter'),
    ]

    operations = [
        migrations.AddField(
            model_name='akte',
            name='drittbeteiligte',
            field=models.ManyToManyField(blank=True, related_name='akten', to='aktenverwaltung.drittbeteiligter'),
        ),
        migrations.AddField(
            model_name='akte',
            name='modus_operandi',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
