# Generated by Django 5.2.8 on 2025-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0006_aktedrittbeteiligter_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='akte',
            name='drittbeteiligte_historie',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
