# Generated by Django 5.2.8 on 2025-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0007_akte_drittbeteiligte_historie'),
    ]

    operations = [
        migrations.AddField(
            model_name='akte',
            name='fragebogen_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='akte',
            name='fragebogen_historie',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
