# Generated by Django 5.2.8 on 2025-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0008_akte_fragebogen_data_akte_fragebogen_historie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='mandant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mandant',
            name='typ',
        ),
        migrations.AddField(
            model_name='mandant',
            name='ansprache',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Firma', 'Firma')], default='Herr', max_length=20),
        ),
        migrations.AddField(
            model_name='mandant',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mandant',
            name='land',
            field=models.CharField(blank=True, default='Deutschland', max_length=100),
        ),
        migrations.AddField(
            model_name='mandant',
            name='nachname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mandant',
            name='plz',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mandant',
            name='rechtsschutz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandant',
            name='rechtsschutz_bei',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mandant',
            name='stadt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mandant',
            name='strasse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mandant',
            name='vorname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mandant',
            name='vst_berechtigt',
            field=models.BooleanField(default=False),
        ),
    ]
