# Generated by Django 5.2.8 on 2025-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0009_remove_mandant_adresse_remove_mandant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandant',
            name='notizen',
            field=models.TextField(blank=True),
        ),
    ]
