# Generated by Django 5.2.8 on 2025-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktenverwaltung', '0010_mandant_notizen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gegner',
            options={'verbose_name_plural': 'Gegner'},
        ),
        migrations.RemoveField(
            model_name='gegner',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='gegner',
            name='bankverbindung',
        ),
        migrations.AddField(
            model_name='gegner',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gegner',
            name='land',
            field=models.CharField(default='Deutschland', max_length=100),
        ),
        migrations.AddField(
            model_name='gegner',
            name='plz',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='gegner',
            name='stadt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gegner',
            name='strasse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gegner',
            name='typ',
            field=models.CharField(choices=[('Person', 'Person'), ('Firma', 'Firma'), ('Versicherung', 'Versicherung')], default='Versicherung', max_length=20),
        ),
    ]
