# Generated by Django 4.2.9 on 2025-11-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('POWERUSER', 'Power User'), ('USER', 'Benutzer'), ('BETRACHTER', 'Betrachter')], max_length=20),
        ),
    ]
