# Generated by Django 4.2.9 on 2025-11-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aktenverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=255)),
                ('inhalt', models.TextField()),
                ('akte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizen', to='aktenverwaltung.akte')),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Frist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('frist_datum', models.DateField()),
                ('prioritaet', models.CharField(choices=[('hoch', 'Hoch'), ('mittel', 'Mittel'), ('niedrig', 'Niedrig')], default='mittel', max_length=16)),
                ('erledigt', models.BooleanField(default=False)),
                ('akte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fristen', to='aktenverwaltung.akte')),
            ],
            options={
                'ordering': ['frist_datum'],
            },
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('faellig_am', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='offen', max_length=32)),
                ('akte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='aktenverwaltung.akte')),
            ],
            options={
                'ordering': ['faellig_am', 'status'],
            },
        ),
    ]
